name: Deploy to Hostinger

on:
  push:
    branches: [production]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          composer install --no-dev --prefer-dist --optimize-autoloader

      - name: Setup SSH Environment
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.HOSTINGER_SSH_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          # Verify key is valid
          ssh-keygen -l -f ~/.ssh/deploy_key
          # Add host to known_hosts
          ssh-keyscan -p ${{ secrets.HOSTINGER_PORT || 22 }} ${{ secrets.HOSTINGER_HOST }} >> ~/.ssh/known_hosts

      - name: Upload files via SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOSTINGER_HOST }}
          username: ${{ secrets.HOSTINGER_USERNAME }}
          key: ${{ secrets.HOSTINGER_SSH_KEY }}  # Using key content directly
          port: ${{ secrets.HOSTINGER_PORT || 22 }}
          source: "./*"
          target: "/home/u923189910/domains/happniess-perfume.com/public_html/system"
          strip_components: 1
          overwrite: true
          rm: false

      - name: Run migrations and optimize
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOSTINGER_HOST }}
          username: ${{ secrets.HOSTINGER_USERNAME }}
          key: ${{ secrets.HOSTINGER_SSH_KEY }}
          port: ${{ secrets.HOSTINGER_PORT || 22 }}
          script: |
            cd /home/u923189910/domains/happniess-perfume.com/public_html/system
            php artisan down
            php artisan migrate
            php artisan optimize
            php artisan cache:clear
            php artisan view:clear
            php artisan route:clear
            php artisan config:cache
            php artisan up
