name: Deploy to Hostinger

on:
  push:
    branches: [ production ] # Change this to your production branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        composer install --no-dev --prefer-dist --optimize-autoloader

    - name: Upload files via SSH
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOSTINGER_HOST }}
        username: ${{ secrets.HOSTINGER_USERNAME }}
        key: ${{ secrets.HOSTINGER_SSH_KEY }}
        port: ${{ secrets.HOSTINGER_PORT }}
        source: "./*"
        target: "/home/u923189910/domains/happniess-perfume.com/public_html/system" # Update this path
        strip_components: 1

    - name: Run migrations and optimize
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOSTINGER_HOST }}
        username: ${{ secrets.HOSTINGER_USERNAME }}
        key: ${{ secrets.HOSTINGER_SSH_KEY }}
        port: ${{ secrets.HOSTINGER_PORT }}
        script: |
          cd /home/u923189910/domains/happniess-perfume.com/public_html/system # Update this path
          php artisan migrate
          php artisan optimize
          php artisan cache:clear
          php artisan view:clear
          php artisan route:clear
          php artisan config:cache
